### ISSUE TITLE
Make error reporting easy

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/vanilla-installer#16]
As suggested in https://github.com/Fabulously-Optimized/vanilla-installer/issues/14#issuecomment-1276302394

**Comment by osfanbuff63** [comment]
On the GUI version, there's a button to report bugs:

![image](https://user-images.githubusercontent.com/91388253/199564339-904a41ee-8552-4b00-8491-39d4f802b87d.png)

However, there's no CLI command to do this. Thankfully, it would be as easy as just making a single function, so I can do that, since it'll likely just open in a webbrowser since I don't want to try to make a whole `gh` all over again lol

**Comment by osfanbuff63** [comment]
Update: The CLI now has this feature, so this issue can probably be closed, unless you want to do something else with either frontend.

**Comment by nsde** [comment]
Thanks! The new GUI looks great 🔥
