### ISSUE TITLE
[Bug]: No requirements.txt?

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/vanilla-installer#40]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

There is no `requirements.txt` in the root directory of this project.
Is this intentional or should I create one? If so, where?

### Version

Development commit (manually installed)

### What platform are you using?

Windows, Linux

### How did you download the software?

Built from source

**Comment by osfanbuff63** [comment]
It's complicated, since there's [some problems with `requirements.txt`](https://modelpredict.com/wht-requirements-txt-is-not-enough). This project currently contains lockfiles for [Poetry](https://python-poetry.org) (as of #36), so you'll probably need to [install it](https://python-poetry.org/docs/#installation) first. [More on Python dependency tools](https://modelpredict.com/python-dependency-management-tools).

**Comment by RozeFound** [comment]
As far as I remember you don't need to install poetry if you only want to install the package. You just do `pip install .` from project root directory and this is it. You do need potery if you plan to take a part in development and be able to debug code tho
In both cases `requirements.txt` isn't necessary

**Comment by osfanbuff63** [comment]
^
closing this so it doesn't try to tell me i have more open issues lol
