### ISSUE TITLE
[Bug]: GUI takes too long to open

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#55]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The installer seems to take up to 10 seconds to open, on a computer with a M.2 SSD. Why? Please reduce that delay. 

Related: #54 

### Version

Beta release

### What platform are you using?

Windows

### How did you download the software?

GitHub Releases

**Comment by osfanbuff63** [comment]
With my improvements regarding #54, this doesn't seem to be much of an issue for me. This was actually the longest time I recorded - besides times where I forgot to stop/start the timer or I forgot to start the program. Time recorded with [LiveSplit](https://livesplit.org) because that's literally the first thing I thought of that I had installed 😅 

https://user-images.githubusercontent.com/91388253/217119401-c3d6f97e-61a7-4f8c-b642-fc0fe477d940.mp4

(As you can see, the time was more like 2.00 sec, but reaction time lol)

**Comment by Madis0** [comment]
Can confirm that the time is about 2-3 sec, which is acceptable.
