### ISSUE TITLE
[Feature Request]: Rename/simplify "data" folder

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#60]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Potential Enhancement

Upon installing FO, the installer creates a "data" folder. That name should be more descriptive

### How it could be implemented

Rename it to "Vanilla Installer Data" or similar. 
Does it even need to be a folder that contains two files? How about just _one_ .json or .cfg file?

**Comment by osfanbuff63** [comment]
Yeah, I had considered making this some sort of config file - this was original when I started work on the project, and so that's been the 'tradition' so to speak. I do agree that one `vanilla-installer.cfg` or similar would be better.

**Comment by osfanbuff63** [comment]
The only problem with the above solution...is the constant config file type debate. Here's some options off the top of my head:

**Python's ini-like `configparser` format**
Since the library is already built into Python, it makes it a bit easier to do - however, its format is relatively unique and doesn't have a ton of specific standards afaik.

**JSON**
Another that's built into Python. This is a good option, but we can't use comments in JSON and it's not the *most* readable format on this list.

**TOML**
This would personally be my go-to. Since we already have `tomllib` on 3.11 and `tomli`, it wouldn't be hard to add the write companion. The advantages also include having a readable config file format - so if someone wants to look at just what are we storing in said config file, it's very easy to do. Comments can also show 

Those are probably the best options, but I'm open to other suggestions.

**Comment by Madis0** [comment]
We don't need comments in the config file, these can be just documented to wiki itself. GUI users wouldn't need to edit it anyway and CLI users are used to wikis 😛

**Comment by nsde** [comment]
> CLI users are used to wikis

As someone who managed quite a few Minecraft servers, having comments in config files is really useful.
So sorry, but I have to disagree here.
